src/routes/media.py
from os import makedirs, path
from urllib.parse import unquote
from zipfile import ZipFile

from flask import Blueprint, send_file

# from pmv import settings
import database as db
from .helpers import require_permission
from .music import bp as ms, pl, al
from json import dumps

bp = Blueprint('media', __name__)


# TODO: Scrap or rework big-time
@bp.route('/torrent/<artist_name>/<album_name>', methods=['POST'])
@require_permission(db.Permission.music_can_download)
def torrent(artist_name, album_name):
    torrent_path = "torrents/" + artist_name + "/" + album_name + ".torrent"

    return send_file(torrent_path, as_attachment=True, attachment_filename=album_name + '.torrent')


@al.route('/<int:album_id>/zip', methods=['POST'])
@al.route('/<int:album_id>/zip/<int:disc>', methods=['POST'])
@pl.route('/<int:playlist_id>/zip/', methods=['POST'])
@require_permission(db.Permission.music_can_download)
def zip(album_id: int = None, playlist_id: int = None, disc: int = None):
    import pmv
    if album_id:
        item = db.get_album_by_id(album_id)
        if disc:
            tracks = db.get_album_disc_by_id(album_id, disc)
            filename = "/etc/pmv/zips/%s/%s-%r.zip" % (item.artist_name, item.name, disc)
        else:
            tracks = item.tracks
            filename = "/etc/pmv/zips/%s/%s.zip" % (item.artist_name, item.name)
    else:
        item = db.get_playlist_by_id(playlist_id)
        tracks = item.tracks
        filename = "/etc/pmv/zips/playlists/%s/%s.zip" % (item.creator, item.name)

    if not path.exists(path.dirname(filename)):
        makedirs(path.dirname(filename))

    if not path.isfile(filename) or playlist_id:
        z = ZipFile(filename, 'w')
        for track in tracks:
            z.write(pmv.settings['music_library'] + unquote(track.download_url), arcname=unquote(track.download_url))
        z.close()

    return send_file(filename, as_attachment=True, attachment_filename='%s%s.zip'
                                                                       % (item.name,
                                                                          '-%s' % disc if disc else ''))


@al.route('/<int:album_id>/image')
@al.route('/<int:album_id>/image/<int:width>')
@ms.route('/image/<string:artist_name>/<string:album_name>')
@ms.route('/image/<string:artist_name>/<string:album_name>/<int:width>')
# @login_required
# @require_permission(db.PermissionType.MUSIC, db.Permission.VIEW)
def image(album_id: int = None, artist_name: str = None, album_name: str = None, width: int = None):
    import images
    if artist_name and album_name:
        album = db.get_album_by_name(artist_name, album_name)
    else:
        album = db.get_album_by_id(album_id)

    if not album:
        album = db.Album(name=album_name, artist_name=artist_name)
    image = images.get_image(album, width)
    if image:
        return send_file(image, mimetype='image/png')
    else:
        return dumps({"message": "No album art could be found for the given artist and album name."})

src/routes/music.py
import datetime
import operator
from functools import reduce
from urllib.parse import unquote

from flask import render_template, redirect, url_for, Blueprint, send_file, request, flash, make_response
from magic import Magic

import database as db
from helper import get_current_user
from .helpers import require_permission, get_json_response, wants_html

bp = Blueprint('music', __name__, url_prefix='/music')
al = Blueprint('album', __name__, url_prefix='/music/album')
tr = Blueprint('track', __name__, url_prefix='/music/track')
pl = Blueprint('playlist', __name__, url_prefix='/music/playlist')


@bp.route('/artist')
@bp.route("/artist/<int:artist_id>")
@require_permission(db.Permission.music_can_view)
def artist(artist_id: int = None):
    if artist_id:
        artist = db.get_artist_by_id(artist_id)
        albums = artist.albums
        albums.sort(key=lambda x: x.release_date or datetime.date(datetime.MINYEAR, 1, 1), reverse=True)

        if 'text/html' in request.accept_mimetypes:
            return_data = render_template('table.html', albums=albums, title=artist.name)
        else:
            return_data = get_json_response(albums)
    else:
        artists = db.get_artists()
        artists.sort(key=lambda x: x.name_sort)
        if wants_html():
            return_data = render_template('table.html', artists=artists, title="Artists")
        else:
            return_data = get_json_response(artists)
    return return_data


@al.route("/<int:album_id>")
@require_permission(db.Permission.music_can_view)
def album(album_id: int):
    import pmv
    album = db.get_album_by_id(album_id)
    tracks = album.tracks
    tracks = sorted(tracks, key=lambda x: (x.disc_num, x.track_num))

    if wants_html():
        return render_template('table.html', tracks=tracks, title=album.name, key=album.id, parentKey=album.artist_key,
                               parentTitle=album.artist_name, settings=pmv.settings, totalSize=album.total_size())
    else:
        return get_json_response(tracks)


@tr.route("/<int:track_id>")
def track(track_id: int):
    import images
    import lyrics
    track = db.get_track_by_id(track_id)

    playlists = db.get_playlists_by_user(get_current_user())
    # track.album

    banner_colour = images.get_predominant_colour(track.album)
    button_colour = images.get_button_colour(banner_colour)
    text_colour = images.get_text_colour(banner_colour)

    if wants_html():
        return render_template('track.html', track=track,
                               banner_colour=banner_colour, text_colour=text_colour, button_colour=button_colour,
                               lyrics=lyrics.get_song_lyrics(track)
                               .split('\n'), playlists=playlists)
    else:
        return get_json_response(track, max_depth=1)


@tr.route("/<int:track_id>/file")
@tr.route("/<int:track_id>/file/<download>")
@require_permission(db.Permission.music_can_download)
def track_file(track_id: int, download=False):
    import pmv
    track = db.get_track_by_id(track_id)

    file_path = pmv.settings['music_library'] + unquote(track.download_url)

    mime = Magic(mime=True)
    mimetype = mime.from_file(file_path)

    return send_file(file_path, mimetype=mimetype,
                     as_attachment=download, attachment_filename='%s.%s' % (track.name, track.format))


@pl.route('/')
@require_permission(db.Permission.music_can_view)
def playlists():
    playlists = db.get_playlists_by_user(get_current_user()) or []

    if wants_html():
        return render_template('playlists.html', playlists=playlists)
    else:
        return get_json_response(playlists)


@pl.route('/<int:playlist_id>')
@require_permission(db.Permission.music_can_view)
def playlist(playlist_id: int):
    import pmv
    playlist = db.get_playlist_by_id(playlist_id)

    if wants_html():
        return render_template('table.html', tracks=playlist.tracks, title=playlist.name, settings=pmv.settings,
                               is_playlist=True, key=playlist_id,
                               totalSize=reduce(operator.add, [track.size for track in playlist.tracks]))
    else:
        tracks = [*map(lambda x: x.id, playlist.tracks)]
        return get_json_response(playlist, max_depth=1, append={'tracks': tracks})


@pl.route('/add/<string:name>', methods=['POST'])
@require_permission(db.Permission.music_can_view)
def create_playlist(name: str):
    playlist = db.Playlist(name=name, creator_id=get_current_user().id)
    db.add_single(playlist)

    return redirect(request.referrer)


@pl.route('/<int:playlist_id>/add/<int:track_id>', methods=['POST'])
@pl.route('/<int:playlist_id>/add/<int:track_id>/<string:playlist_name>', methods=['POST'])
@pl.route('/add/<int:track_id>', methods=['POST'])
@pl.route('/add/<int:track_id>/<string:playlist_name>', methods=['POST'])
@require_permission(db.Permission.music_can_view)
def add_to_playlist(track_id: int, playlist_id: int = None, playlist_name: str = None):
    if not playlist_id:
        playlist_id = int(request.form.get('playlist_id'))

    if playlist_id == -1:
        if not playlist_name:
            playlist_name = request.form.get('playlist_name')
        playlist = db.Playlist(name=playlist_name, creator_id=get_current_user().id)
    else:
        playlist = db.get_playlist_by_id(playlist_id)

    track = db.get_track_by_id(track_id)

    # Check track not already in playlist
    f = [*filter(lambda track: track.id == track_id, playlist.tracks)]
    if not f or len(f) == 0:
        playlist.tracks.append(track)
        db.session().commit()

    return redirect(request.referrer)


@tr.route('/<int:track_id>/lyrics', methods=['GET', 'POST'])
@require_permission(db.Permission.music_can_edit)
def lyrics(track_id: int):
    import lyrics
    current_track = db.get_track_by_id(track_id)

    if request.method == "POST":
        lyrics.update_lyrics(current_track, request.form.get('lyrics'))

        flash('Lyrics successfully updated', category='success')
        return redirect(url_for('music.track', track_id=track_id))

    lyrics = lyrics.get_song_lyrics(current_track)
    response = make_response(lyrics, 200)
    response.mimetype = "text/plain"
    return response


@tr.route('/<int:track_id>/metadata', methods=['POST'])
@require_permission(db.Permission.music_can_edit)
def update_metadata(track_id: int):
    print(request.form)
    return str(track_id)  # TODO Write metadata updating (local, database, plex)


@bp.route("/search", methods=['GET', 'POST'])
@bp.route("/search/<query>", methods=['GET', 'POST'])
@require_permission(db.Permission.music_can_view)
def search(query=None, for_artists=True, for_albums=True, for_tracks=True):
    if not query:
        query = request.form.get('query')

    if for_artists:
        artists = db.get_artists_by_name(query)

    if for_albums:
        albums = db.get_albums_by_name(query)

    if for_tracks:
        tracks = db.get_tracks_by_name(query)

    if wants_html():
        return render_template('table.html', artists=artists, albums=albums, tracks=tracks, title=query,
                               is_search=True, prev=request.referrer)
    else:
        return get_json_response({'artists': artists, 'albums': albums, 'tracks': tracks}, max_depth=3)

src/templates/tables/albums.html
{% if not is_search %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url_for('music.artist') }}">Artists</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ title }}</li>
        </ol>
    </nav>
{% endif %}
<table class="table table-striped">
    <tbody id="album_table">
    <tr>
        <th>Album Name</th>
        <th>Release Date</th>
        <th>Track Count</th>
        {% if is_search %}
            <th>Artist</th>
        {% endif %}
    </tr>
    {% for album in albums %}
        <tr>
            <td><a href="{{ url_for('album.album', album_id=album.id) }}">{{ album.name }}</a></td>
            <td>{{ (album.release_date if album.release_date.month != 1 and album.release_date.day != 1
                    else album.release_date.year) if album.release_date else 'N/A' }}</td>
            <td>{{ album.track_count }}</td>
            {% if is_search %}
                <td><a href="{{ url_for('music.artist', artist_key=album.artist_key) }}">{{ album.artist_name }}</a></td>
            {% endif %}
        </tr>
    {% endfor %}
    </tbody>
</table>

src/templates/tables/artists.html
<table class="table table-striped">
    <tbody id="artist_table">
        <tr>
            <th>Artist Name</th>
            <th>Album Count</th>
        </tr>
        {% for artist in artists %}
            <tr>
                <td><a href="{{ url_for('music.artist', artist_id=artist.id) }}">{{ artist.name }}</a></td>
                <td>{{ artist.album_count }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

src/templates/tables/tracks.html
<audio id="audio" preload="auto"></audio>
<div class="row">
    <!-- Page tools -->
    {% if not is_search and not is_playlist %}
        <div class="col-md">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ url_for('music.artist') }}">Artists</a></li>
                    <li class="breadcrumb-item"><a
                            href="{{ url_for('music.artist', artist_id=parentKey) }}">{{ parentTitle }}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{ title }}</li>
                </ol>
            </nav>
        </div>
        <div class="row col-md">
            <form class="form-inline my-2 my-lg-1 mr-1"
                  action="{{ url_for('album.zip', album_id=key) }}" method="post">
                <button class="btn btn-outline-success my-sm-0" type="submit">Download album
                    ({{ format_size(totalSize) }})
                </button>
            </form>
            <form class="form-inline my-2 my-lg-1 ml-1"
                  action="{{ url_for('media.torrent', artist_name=parentTitle, album_name=title) }}" method="post">
                <button disabled class="btn btn-outline-success my-sm-0" type="submit">Download torrent</button>
            </form>
        </div>
    {% endif %}
    {% if is_playlist %}
        <div class="row col-md">
            <form class="form-inline my-2 my-lg-1 mr-1"
                  action="{{ url_for('playlist.zip', playlist_id=key) }}" method="post">
                <button class="btn btn-outline-success my-sm-0" type="submit">Download playlist
                    ({{ format_size(totalSize) }})
                </button>
            </form>
            <form class="form-inline my-2 my-lg-1 ml-1"
                  action="{{ url_for('media.torrent', artist_name=parentTitle, album_name=title) }}" method="post">
                <button disabled class="btn btn-outline-success my-sm-0" type="submit">Download torrent</button>
            </form>
        </div>
    {% endif %}
</div>
<table class="table table-striped">
    <tbody id="track_table">
    <tr>
        <th style="width: 12%;">Track No.</th>
        <th>Track</th>
        <th>Playtime</th>
        <th>Bitrate</th>
        <th>Format</th>
        <th>Size</th>
        {% if is_search or is_playlist %}
            <th>Album</th>
            <th>Artist</th>
        {% endif %}
    </tr>
    {% set last = tracks|last %}
    {% set discs = [0] %}
    {% for track in tracks %}
        {% if not is_search and not is_playlist %}
            {% if int(last.disc_num) > 1 and int(track.disc_num) != int(discs|last) %}
                <tr class='discrow'>
                    <td>
                        <div class="row">
                            <div class="col-4">
                                <form class="form-inline my-2 my-lg-1 mr-1"
                                      action="{{ url_for('album.zip', album_id=key, disc=track.disc_num) }}"
                                      method="post">
                                    <button class="btn btn-link" type="submit"><span
                                            class="oi oi-data-transfer-download"></span>
                                    </button>
                                </form>
                            </div>
                            <div class="col">
                                <h6 style="position: absolute; top: 12px">
                                    <b>Disc {{ track.disc_num }}</b>
                                </h6>
                            </div>
                        </div>
                    </td>
                </tr>
                {% if discs.append(track.disc_num) %}{% endif %}
            {% endif %}
            <tr>
        {% endif %}
    <td class="row">
        <div class="col-2">
            {{ track.track_num }}
        </div>
        <div class="btn-group" role="group">
            <button class="btn btn-link" onclick="play(`{{ url_for('track.track_file', track_id=track.id) }}`);">
                <span id="play-{{ track.id }}"
                      class="oi oi-media-play"></span></button>
            <a class="btn btn-link" href="{{ url_for('track.track_file', track_id=track.id, download='1') }}">
                <span class="oi oi-data-transfer-download"></span></a>
        </div>

    </td>
    <td><a href="{{ url_for('track.track', track_id=track.id) }}">{{ track.name }}</a></td>
    <td>{{ format_duration(track.duration) }}</td>
    <td>{{ track.bitrate }}kbps</td>
    <td>{{ track.format }}</td>
    <td>{{ format_size(track.size) }}</td>
    {% if is_search or is_playlist %}
        <td><a href="{{ url_for('album.album', album_id=track.album_key) }}">{{ track.album_name }}</a></td>
        <td><a href="{{ url_for('music.artist', artist_id=track.artist_key) }}">{{ track.artist_name }}</a>
        </td>
    {% endif %}
    </tr>
    {% endfor %}
    </tbody>
</table>